version: '3.4'
services:
  hangfire-client:
    image: hangfire-dotnet3-client
    build:
      context: .
      dockerfile: client/Dockerfile
    ports:
      - 80
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
  hangfire-server:
    build:
      context: .
      dockerfile: server/Dockerfile
    image: hangfire-dotnet3-server
  hangfire-server2:
    image: hangfire-dotnet3-server
  mongo:
    image: mongo:4.2-bionic